# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: ['ROLE_USER']
                    admin:
                        password: admin
                        roles: ['ROLE_ADMIN']
        fos_userbundle:
            id: fos_user.user_provider.username
        common_provider:
            chain:
                providers: [fos_userbundle, in_memory]


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            form_login:
                provider: common_provider
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: "/api/user/login_check"
            logout:       true
            anonymous:    true
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            #form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/api/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/admin/, role: ROLE_ADMIN }