API\UserBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        UserLogin:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: last_name
        isActive:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: is_active
        logo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        createAt:
            type: datetime
            nullable: true
            comment: ''
            column: create_at
        updateAt:
            type: datetime
            nullable: true
            comment: ''
            column: update_at
        lastActivity:
            type: datetime
            nullable: true
            comment: ''
            column: last_activity
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        preRemove: [ storeFilenameForRemove ]
        postRemove: [ removeUpload ]
