services:
#    api_user.example:
#        class: API\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    api_user.rss_handler:
        class: API\UserBundle\View\RSSViewHandler

    api_user.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'rss', [@api_user.rss_handler, 'createResponse'] ] ]
